name: seq_demo-environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numpy
  - pandas-datareader>=0.5.0
  - matplotlib
  - qgrid
  - biopython
  - intermine
  - seaborn
  - scipy
  - statsmodels
