name: seq_demo-environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numpy
  - pandas-datareader>=0.5.0
  - jupyterlab>=1.0
  - matplotlib=3.1.2
  #- qgrid
  - biopython
  - intermine
  - seaborn
  - scipy
  - statsmodels
