name: seq_demo-environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - numpy
  - pandas-datareader>=0.5.0
  - jupyterlab>=1.0
  - matplotlib
  #- qgrid
  - biopython
  - seaborn
  - scipy
  - statsmodels
  - hhsuite
  - nbgitpuller
  - pip
  - pip:
    - https://github.com/intermine/intermine-ws-python/archive/dev.zip
